name: RoleplayEssentials
main: me.nouma.rpe.Main
version: 0.1
author: Nouma
description: All your needs for your RP server !
website: https://discord.gg/Hx393nu
depends: [Vault] #[HolographicDisplays]
commands:
  rpe:
    description: 'Plugin''s main command.'
    permission: rpe.admin
    aliases:
      - roleplayessentials
  advert:
    description: 'Broadcast an advert to all citizens.'
    permission: rpe.advert
    usage: '§8Correct usage: §c/advert <message>'
    aliases:
      - pub
  name:
    description: 'Change your character''s name.'
    permission: rpe.id.name
    usage: '§8Correct usage: §c/name <first_name> <second_name>'
    aliases:
      - nom
      - identity
      - identite
      - character
      - personnage
  id:
    description: 'Manage identites.'
    permission: rpe.id
    usage: '§8Correct usage: §c/id <give/check>'